//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishLand_FrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class credential
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public credential()
        {
            this.orders = new HashSet<order>();
        }
    
        public int credentialsID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int userID { get; set; }
        public int userTypeID { get; set; }
    
        public virtual user user { get; set; }
        public virtual userType userType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
