//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishLand_FrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.credentials = new HashSet<credential>();
        }
    
        public int userID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string cellphone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public int userTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<credential> credentials { get; set; }
        public virtual userType userType { get; set; }
    }
}
